### ISSUE TITLE
"Something went wrong..." when trying to execute command on multiple hosts

### ISSUE THREAD

**Issue by unbreakabl3** [ansible/awx-operator#696]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
We have a smart inventory, which includes all hosts. When we're selecting all of them and wants to execute some command by clicking in `Run Command` button, we're getting the error (screenshot and message below)

##### ENVIRONMENT
* AWX version: 19.5.0
* Operator version: 0.15.0
* Kubernetes version: v1.20.7
* AWX install method: via operator on regular Kubernetes cluster

##### STEPS TO REPRODUCE

select multiple hosts and click on `Run Command` button

##### EXPECTED RESULTS

should be able to execute command on multiple hosts

##### ACTUAL RESULTS

![Screenshot 2021-12-14 at 13 23 51](https://user-images.githubusercontent.com/13556249/145998114-74d36d1f-9002-4ae8-9135-2d2843e638d6.png)

![Screenshot 2021-12-14 at 13 23 26](https://user-images.githubusercontent.com/13556249/145998800-a482f987-05f9-4d3c-8302-b6e892503906.png)

```
dv@https://test.domain.local/static/js/main.7b1f208d.chunk.js:1:581425 
Zo@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1419512 
Ss@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1465743 
vl@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1458470 
ml@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1458395 
sl@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1455404 
sl@[native code] 
@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1406774 
@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1482175 
Yi@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1406720 
Xi@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1406655 
R@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1475941 
Yt@https://test.domain.local/static/js/2.97a1dff5.chunk.js:2:1383925 
Yt@[native code]

**Comment by AlanCoding** [comment]
Could you check if there are any relevant server logs? Depending on what that shows, this may be more appropriate in the AWX issue tracker.

**Comment by unbreakabl3** [comment]
There are no any messages in the logs when clicking on the `Run Command` button. Nothing happened not in the `awx-web`. In `awx-task` pod I can see the following:
```
RESULT 2
OKREADY
2021-12-20 11:44:39,714 DEBUG    [-] awx.main.commands.run_callback_receiver 317 is alive
2021-12-20 11:44:39,714 DEBUG    [-] awx.main.commands.run_callback_receiver 317 is alive
2021-12-20 11:44:39,716 ERROR    [-] awx.conf.settings Database settings are not available, using defaults.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/postgresql/base.py", line 223, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/conf/settings.py", line 81, in _ctit_db_wrapper
    yield
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/conf/settings.py", line 405, in __getattr__
    value = self._get_local(name)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/conf/settings.py", line 327, in _get_local
    self._preload_cache()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/conf/settings.py", line 296, in _preload_cache
    for setting in Setting.objects.filter(key__in=settings_to_cache.keys(), user__isnull=True).order_by('pk'):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor = self.connection.cursor()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/postgresql/base.py", line 223, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
```

I did re-create the container, but even after that the behaviour is exactly the same.
